/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as LuuNiemRouteImport } from './routes/luu-niem'
import { Route as ThanhToanRouteImport } from './routes/thanh-toan'
import { Route as VeRouteImport } from './routes/ve'
import { Route as DonHangCodeRouteImport } from './routes/don-hang.$code'
import { Route as ApiPublicSepayWebhookRouteImport } from './routes/api/public/sepay-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const LuuNiemRoute = LuuNiemRouteImport.update({
  id: '/luu-niem',
  path: '/luu-niem',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanhToanRoute = ThanhToanRouteImport.update({
  id: '/thanh-toan',
  path: '/thanh-toan',
  getParentRoute: () => rootRouteImport,
} as any)
const VeRoute = VeRouteImport.update({
  id: '/ve',
  path: '/ve',
  getParentRoute: () => rootRouteImport,
} as any)
const DonHangCodeRoute = DonHangCodeRouteImport.update({
  id: '/don-hang/$code',
  path: '/don-hang/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSepayWebhookRoute = ApiPublicSepayWebhookRouteImport.update({
  id: '/api/public/sepay-webhook',
  path: '/api/public/sepay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/lien-he': typeof LienHeRoute
  '/luu-niem': typeof LuuNiemRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/ve': typeof VeRoute
  '/don-hang/$code': typeof DonHangCodeRoute
  '/api/public/sepay-webhook': typeof ApiPublicSepayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/lien-he': typeof LienHeRoute
  '/luu-niem': typeof LuuNiemRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/ve': typeof VeRoute
  '/don-hang/$code': typeof DonHangCodeRoute
  '/api/public/sepay-webhook': typeof ApiPublicSepayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/lien-he': typeof LienHeRoute
  '/luu-niem': typeof LuuNiemRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/ve': typeof VeRoute
  '/don-hang/$code': typeof DonHangCodeRoute
  '/api/public/sepay-webhook': typeof ApiPublicSepayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/lien-he'
    | '/luu-niem'
    | '/thanh-toan'
    | '/ve'
    | '/don-hang/$code'
    | '/api/public/sepay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/lien-he'
    | '/luu-niem'
    | '/thanh-toan'
    | '/ve'
    | '/don-hang/$code'
    | '/api/public/sepay-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/lien-he'
    | '/luu-niem'
    | '/thanh-toan'
    | '/ve'
    | '/don-hang/$code'
    | '/api/public/sepay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LienHeRoute: typeof LienHeRoute
  LuuNiemRoute: typeof LuuNiemRoute
  ThanhToanRoute: typeof ThanhToanRoute
  VeRoute: typeof VeRoute
  DonHangCodeRoute: typeof DonHangCodeRoute
  ApiPublicSepayWebhookRoute: typeof ApiPublicSepayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luu-niem': {
      id: '/luu-niem'
      path: '/luu-niem'
      fullPath: '/luu-niem'
      preLoaderRoute: typeof LuuNiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanh-toan': {
      id: '/thanh-toan'
      path: '/thanh-toan'
      fullPath: '/thanh-toan'
      preLoaderRoute: typeof ThanhToanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ve': {
      id: '/ve'
      path: '/ve'
      fullPath: '/ve'
      preLoaderRoute: typeof VeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/don-hang/$code': {
      id: '/don-hang/$code'
      path: '/don-hang/$code'
      fullPath: '/don-hang/$code'
      preLoaderRoute: typeof DonHangCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sepay-webhook': {
      id: '/api/public/sepay-webhook'
      path: '/api/public/sepay-webhook'
      fullPath: '/api/public/sepay-webhook'
      preLoaderRoute: typeof ApiPublicSepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LienHeRoute: LienHeRoute,
  LuuNiemRoute: LuuNiemRoute,
  ThanhToanRoute: ThanhToanRoute,
  VeRoute: VeRoute,
  DonHangCodeRoute: DonHangCodeRoute,
  ApiPublicSepayWebhookRoute: ApiPublicSepayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
